packaging_format = 2

id = "tooljet"
name = "ToolJet"
description.en = "Framework for building React-based Web applications and internal tools"
description.fr = "Construction d'applications Web basées sur React et d'outils internes"
version = "3.20.188~ynh1"

maintainers = ["Tagadda"]

[upstream]
license = "AGPL-3.0"
website = "https://tooljet.com/"
userdoc = "https://docs.tooljet.com/docs/intro"
code = "https://github.com/ToolJet/ToolJet"
cpe = "cpe:2.3:a:tooljet:tooljet"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "3G"
ram.build = "3G"
ram.runtime = "300M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/ToolJet/ToolJet/archive/refs/tags/v3.20.188-lts.tar.gz"
        sha256 = "0a69f6dea8801b603f09fe035d3448b3aa4c8670598c5fc65c056ad3779780d7"

        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "v(\\d+\\.\\d+\\.\\d+)-lts"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "postgresql, postgresql-contrib, build-essential, xxd"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "18.18.2"

