#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx

ynh_nodejs_remove

#Drop tooljet database
ynh_psql_db_shell <<< "DROP DATABASE $app-db;"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
