#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

# Cleanup after install
ynh_safe_rm "$install_dir/.cache"
ynh_safe_rm "$install_dir/.npm/_cacache"
ynh_safe_rm "$install_dir/node_modules"
ynh_safe_rm "$install_dir/frontend/node_modules"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

#=================================================
# BUILD THE APPLICATION
#=================================================
ynh_script_progression "Building ToolJet..."

pushd $install_dir

	# The version shipped by default with n does not work, there is a

	# wierd dependency issue about unsupported platform and fsevent.
	# See https://github.com/ToolJet/ToolJet/pull/1752
	npm install npm@"$NPM_VERSION" --location=global

	ynh_hide_warnings ynh_exec_as_app node_load_PATH npm install -f
	ynh_hide_warnings ynh_exec_as_app node_load_PATH npm run build
popd

chown $app:www-data -R "$install_dir/frontend/build"
chown $app:www-data "$install_dir/frontend/build"
chown $app:www-data "$install_dir/frontend"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template=".env.example" --destination="$install_dir/.env"

#=================================================
# BUILD THE DATABASE
#=================================================
ynh_script_progression "Building ToolJet database..."

pushd $install_dir
	# Build the database once the configuration is set
	ynh_exec_as_app npm run db:migrate
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
